spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/terminal_code
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

logging:
  level:
    terminal_code.backend: DEBUG
